all:
  children:
    camera_hosts:
      hosts:
        razorcrest:
          ansible_user: benvh
          prometheus_arch: arm64
        picam[01:04]:
        picam01:
          camera_tuning_file: ov5647
        picam02:
          camera_tuning_file: imx296
        picam03:
          camera_tuning_file: ov5647_noir
        picam04:
          camera_tuning_file: imx219_noir
      vars:
        camera_user: camera_stream
        ansible_user: pi
    camera_monitors:
      hosts:
        razorcrest:
          ansible_user: benvh
        primemover:
          ansible_user: benvh
      vars:
        camera_user: camera_stream
        ansible_user: pi
    fileserver_hosts:
      hosts:
        littlerascal:
          ansible_user: benvh
    camera_controllers:
      children:
        camera_hosts:
        camera_monitors:

