all:
  children:
    camera_hosts:
      hosts:
        razorcrest:
          ansible_user: benvh
          prometheus_arch: arm64
          systemctl: /bin/systemctl
          shutdown: /sbin/shutdown
          reboot: /sbin/reboot
        picam[01:04]:
          multiinstance: false
        picam01:
          camera_tuning_file: ov5647
        picam02:
          camera_tuning_file: imx296
        picam03:
          camera_tuning_file: ov5647_noir
        picam04:
          camera_tuning_file: imx219_noir
      vars:
        camera_user: camera_stream
        ansible_user: pi
        simple_host: true
    camera_monitors:
      hosts:
        razorcrest:
        primemover:
          ansible_user: benvh
          multiinstance: true
        # picam04:
      vars:
        camera_user: camera_stream
        ansible_user: pi
        multiinstance: false
        simple_host: false
    fileserver_hosts:
      hosts:
        littlerascal:
          ansible_user: benvh
    camera_controllers:
      children:
        camera_hosts:
        camera_monitors:
  vars:
    systemctl: /usr/bin/systemctl
    shutdown: /usr/sbin/shutdown
    reboot: /usr/sbin/reboot

